apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "42"
  creationTimestamp: 2018-04-04T21:29:36Z
  generation: 64
  labels:
    app: first-poc
  name: first-poc
  namespace: default
  resourceVersion: "9923979"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/first-poc
  uid: 465046c1-384f-11e8-939e-026e48e999c2
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: first-poc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: first-poc
    spec:
      containers:
      - image: 954082300853.dkr.ecr.sa-east-1.amazonaws.com/hmg/first-poc:138
        imagePullPolicy: Always
        name: first-poc
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: 2018-04-10T19:18:38Z
    lastUpdateTime: 2018-05-16T15:14:05Z
    message: ReplicaSet "first-poc-b954d5646" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2018-07-16T10:05:33Z
    lastUpdateTime: 2018-07-16T10:05:33Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 64
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
